const state={token:localStorage.getItem('kb_token')||'',user:null,documents:[],departments:[],users:[],roles:[],editingDepartment:null,editingUser:null,sessionId:crypto.randomUUID(),lastCitations:[]};
const labels={dashboard:'运营概览',documents:'知识维护',chat:'智能问答',curation:'知识沉淀',organization:'组织与账号'};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
async function api(path,options={}){const token=state.token;const headers={...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{})};const r=await fetch('/api'+path,{...options,headers:{...headers,...options.headers}});let data;try{data=await r.json()}catch{data={detail:r.statusText}}if(!r.ok){if(r.status===401&&token===state.token){logoutLocal()}throw Error(data.detail||'请求失败')}return data}
function resetChat(){state.sessionId=crypto.randomUUID();state.lastCitations=[];$('#chat-messages').innerHTML=$('#chat-messages').dataset.welcome;$('#recent-citations').innerHTML='<div class="empty-small">本次对话的引用将显示在这里</div>';$('#restricted-note').hidden=true;$('#question').value='';$('.send-button').disabled=false}
function logoutLocal(){state.token='';state.user=null;localStorage.removeItem('kb_token');resetChat();$('#app').hidden=true;$('#login').hidden=false;window.scrollTo(0,0)}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';const fd=new FormData(e.currentTarget);try{const result=await api('/login',{method:'POST',body:JSON.stringify(Object.fromEntries(fd))});state.token=result.token;state.user=result.user;localStorage.setItem('kb_token',state.token);await showApp()}catch(err){$('#login-error').textContent=err.message}});
$('#logout').addEventListener('click',async()=>{try{await api('/logout',{method:'POST'})}catch{}logoutLocal()});
function homeView(){const view=['dashboard','chat','documents','curation','organization'].find(name=>state.user.permissions.includes($(`.nav[data-view="${name}"]`).dataset.permission));navigate(view||'access')}
async function showApp(){try{state.user=await api('/me')}catch{return}$('#login').hidden=true;$('#app').hidden=false;window.scrollTo(0,0);$('#user-name').textContent=state.user.display_name;$('#user-avatar').textContent=state.user.display_name.slice(0,1);$('#chat-user').textContent=state.user.display_name;$('#chat-avatar').textContent=state.user.display_name.slice(0,1);$('#chat-dept').textContent=state.user.department_id||'未分配部门';$$('[data-permission]').forEach(n=>{const allowed=state.user.permissions.includes(n.dataset.permission);n.dataset.available=allowed?'true':'false';n.title=allowed?'':'需要管理员授权';n.setAttribute('aria-label',`${n.textContent.trim()}${allowed?'':'，需要管理员授权'}`)});const chatOnly=state.user.permissions.length===1&&state.user.permissions.includes('chat.access');$('#chat-access-summary').textContent=chatOnly?'当前账号已开通智能问答。可直接输入问题，或点击下方示例开始；其他管理功能需要管理员授权。':'';$('#chat-access-summary').hidden=!chatOnly;homeView()}
function navigate(name){const nav=$(`.nav[data-view="${CSS.escape(name)}"]`);const view=$(`#view-${name}`);if(!view)return;if(nav&&!state.user.permissions.includes(nav.dataset.permission)){ $$('.view').forEach(v=>v.hidden=true);$('#view-access').hidden=false;$$('.nav').forEach(n=>n.classList.toggle('active',n===nav));$('#page-crumb').textContent='功能预览';$('#access-title').textContent=`${labels[name]}暂不可用`;$('#access-message').textContent=`当前账号没有“${labels[name]}”功能权限。`;$('#access-detail').textContent='此页面仅提供功能说明，不会读取或修改受保护的数据；如需使用，请联系管理员分配相应角色权限。';return}if(name==='access'){$('#access-title').textContent='当前账号暂无可用功能';$('#access-message').textContent='请联系管理员为此账号分配至少一个功能权限。';$('#access-detail').textContent='此页面不会读取或修改受保护的数据。';}$$('.view').forEach(v=>v.hidden=true);view.hidden=false;$$('.nav').forEach(n=>n.classList.toggle('active',n===nav));$('#page-crumb').textContent=labels[name]||'功能预览';if(name==='dashboard')loadDashboard();if(name==='documents')loadDocuments();if(name==='curation')loadCuration();if(name==='organization')loadOrganization()}
$$('.nav').forEach(n=>n.addEventListener('click',()=>navigate(n.dataset.view)));
$('#brand-home').addEventListener('click',e=>{e.preventDefault();homeView()});$('#access-back').addEventListener('click',homeView);
function metric(label,value,icon,foot){const display=typeof value==='number'?value.toLocaleString():esc(value??'—');return `<div class="metric"><div class="metric-label"><span class="metric-icon">${icon}</span>${label}</div><div class="metric-value">${display}</div><div class="metric-foot">${foot}</div></div>`}
async function loadDashboard(){try{const d=await api('/dashboard');$('#metrics').innerHTML=[metric('问答总量',d.questions,'◌','累计问答轮次'),metric('独立用户',d.uv,'♧','参与提问用户'),metric('知识单元',d.knowledge,'▤','平台知识资产'),metric('Token 消耗',d.tokens,'⌘','估算输入与输出'),metric('平均响应',Number.isFinite(Number(d.avg_latency))?`${Math.round(d.avg_latency)} ms`:'—','◷','检索与处理耗时')].join('');const ranks=(arr,key)=>arr.length?arr.map((x,i)=>`<div class="rank-item"><span class="rank-number ${i<3?'top':''}">${String(i+1).padStart(2,'0')}</span><span class="rank-question" title="${esc(x[key])}">${esc(x[key])}</span><span class="rank-count">${x.count} 次</span></div>`).join(''):'<div class="empty-state">暂无问答数据</div>';$('#top-questions').innerHTML=ranks(d.top_questions,'question');$('#top-knowledge').innerHTML=ranks(d.top_knowledge,'title')}catch(e){toast(e.message)}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadDocuments(){try{state.documents=await api('/documents');renderDocs()}catch(e){toast(e.message)}}
function renderDocs(){const term=$('#doc-search').value.toLowerCase();const docs=state.documents.filter(d=>(d.title+d.category+d.filename).toLowerCase().includes(term));$('#doc-count').textContent=`${docs.length} 个知识单元`;$('#doc-rows').innerHTML=docs.length?docs.map(d=>{const perms=d.permissions;const global=perms.some(p=>p.kind==='global');const label=global?'全局公开':perms.length?perms.map(p=>({department:'部门',role:'角色',user:'个人'}[p.kind])).filter((x,i,a)=>a.indexOf(x)===i).join('、'):'私有';return `<tr><td><div class="doc-title">${esc(d.title)}</div><div class="doc-file">${esc(d.filename)}</div></td><td>${esc(d.category)}</td><td><span class="tag">${esc(d.filename.split('.').pop().toUpperCase())}</span></td><td><span class="tag ${global?'global':'restricted'}">${label}</span></td><td>${d.chunks}</td><td><span class="status ${d.enabled?'published':''}">${d.enabled?'启用':'停用'}</span></td><td><button class="row-action" data-edit="${d.id}">编辑</button><button class="row-action" data-toggle="${d.id}">${d.enabled?'停用':'启用'}</button><button class="row-action" data-acl="${d.id}">权限</button><button class="row-action danger" data-delete="${d.id}">删除</button></td></tr>`}).join(''):'<tr><td colspan="7" class="empty-state">没有匹配的知识单元</td></tr>';$$('[data-acl]').forEach(b=>b.onclick=()=>openAcl(b.dataset.acl));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteDoc(b.dataset.delete));$$('[data-edit]').forEach(b=>b.onclick=()=>editDoc(b.dataset.edit));$$('[data-toggle]').forEach(b=>b.onclick=()=>toggleDoc(b.dataset.toggle))}
async function saveDoc(doc,changes){try{await api(`/documents/${doc.id}`,{method:'PUT',body:JSON.stringify({...doc,...changes})});await loadDocuments()}catch(e){toast(e.message)}}
function editDoc(id){const d=state.documents.find(x=>x.id===id);const title=prompt('知识标题',d.title);if(title===null)return;const category=prompt('所属分类',d.category);if(category===null)return;saveDoc(d,{title,category})}
function toggleDoc(id){const d=state.documents.find(x=>x.id===id);saveDoc(d,{enabled:!d.enabled})}
$('#doc-search').addEventListener('input',renderDocs);
$('#upload-files').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;const input=e.target,status=$('#import-status'),progress=$('#import-progress'),result=$('#import-result');if(files.length>30){toast('单次最多导入30个文件');input.value='';return}input.disabled=true;status.hidden=false;progress.max=files.length;progress.value=0;const imported=[],failed=[];for(const file of files){result.textContent=`正在处理 ${progress.value+1}/${files.length}：${file.name}`;const fd=new FormData();fd.append('files',file);try{const response=await api('/documents/import',{method:'POST',body:fd});imported.push(...response.imported)}catch(err){failed.push(`${file.name}：${err.message}`)}progress.value++;}input.value='';input.disabled=false;result.textContent=`处理完成：成功 ${imported.length} 个，失败 ${failed.length} 个${failed.length?`。${failed.join('；')}`:'；新知识仅当前管理员可见'}`;if(imported.length)await loadDocuments()});
async function deleteDoc(id){if(!confirm('删除该知识单元及其切片？'))return;try{await api(`/documents/${id}`,{method:'DELETE'});await loadDocuments()}catch(e){toast(e.message)}}
async function openAcl(id){try{if(!state.departments.length)state.departments=await api('/departments');if(!state.users.length)state.users=await api('/acl-users');if(!state.roles.length)state.roles=await api('/roles');const d=state.documents.find(x=>x.id===id);$('#acl-title').textContent=d.title;$('#acl-doc-id').value=id;const selected=d.permissions;$('#acl-global').checked=selected.some(p=>p.kind==='global');$('.acl-role-list').innerHTML=state.roles.map(r=>`<label><input type="checkbox" class="acl-role" value="${r.id}" ${selected.some(p=>p.kind==='role'&&p.subject===r.id)?'checked':''}> ${esc(r.name)}</label>`).join('');$('#acl-departments').innerHTML=state.departments.map(x=>`<label><input type="checkbox" class="acl-dept" value="${x.id}" ${selected.some(p=>p.kind==='department'&&p.subject===x.id)?'checked':''}> ${esc(x.name)}</label>`).join('');$('#acl-users').innerHTML=state.users.map(x=>`<label><input type="checkbox" class="acl-user" value="${x.id}" ${selected.some(p=>p.kind==='user'&&p.subject===x.id)?'checked':''}> ${esc(x.display_name)}</label>`).join('');$('#acl-dialog').showModal()}catch(e){toast(e.message)}}
$('#acl-form').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const id=$('#acl-doc-id').value;const permissions=[];if($('#acl-global').checked)permissions.push({kind:'global',subject:'*'});$$('.acl-dept:checked').forEach(x=>permissions.push({kind:'department',subject:x.value}));$$('.acl-role:checked').forEach(x=>permissions.push({kind:'role',subject:x.value}));$$('.acl-user:checked').forEach(x=>permissions.push({kind:'user',subject:x.value}));try{await api(`/documents/${id}/acl`,{method:'PUT',body:JSON.stringify({permissions})});$('#acl-dialog').close();await loadDocuments();toast('访问权限已更新')}catch(err){toast(err.message)}});
$('#chat-messages').addEventListener('click',e=>{const suggestion=e.target.closest('.suggestions button');if(!suggestion)return;$('#question').value=suggestion.textContent;$('#ask-form').requestSubmit()});
$('#new-chat').onclick=()=>{resetChat();$('#question').focus()};
$('#chat-messages').dataset.welcome=$('#chat-messages').innerHTML;
$('#ask-form').addEventListener('submit',async e=>{e.preventDefault();const input=$('#question'),send=$('.send-button'),question=input.value.trim();if(!question||send.disabled)return;send.disabled=true;input.value='';const owner=state.user.id,session=state.sessionId;const welcome=$('.welcome');if(welcome)welcome.remove();addMessage('user',question);const pending=addMessage('assistant','正在检索有权访问的知识…');try{const result=await api('/chat',{method:'POST',body:JSON.stringify({question,session_id:session})});if(state.user?.id!==owner||state.sessionId!==session)return;pending.querySelector('.bubble').textContent=result.answer;const source=pending.querySelector('.answer-sources');if(result.citations.length)source.innerHTML=result.citations.map(c=>`<span class="source-chip" title="${esc(c.excerpt)}">⌕ ${esc(c.title)}</span>`).join('');else source.remove();state.lastCitations=result.citations;$('#recent-citations').innerHTML=result.citations.length?result.citations.map(c=>`<div class="citation-mini"><b>${esc(c.title)}</b><span>${esc(c.excerpt.slice(0,100))}…</span></div>`).join(''):'<div class="empty-small">未引用知识资料</div>';$('#restricted-note').hidden=!result.restricted}catch(err){if(state.user?.id===owner&&state.sessionId===session)pending.querySelector('.bubble').textContent=`请求失败：${err.message}`}finally{if(state.user?.id===owner&&state.sessionId===session)send.disabled=false}});
function addMessage(role,text){const el=document.createElement('div');el.className=`message ${role}`;el.innerHTML=role==='user'?`<div class="bubble"></div>`:`<div class="bubble"><div class="assistant-label">知序 · 知识助手</div><div class="answer-text"></div><div class="answer-sources"></div></div>`;el.querySelector(role==='user'?'.bubble':'.answer-text').textContent=text;$('#chat-messages').append(el);$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;return el}
$('#question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#ask-form').requestSubmit()}});
$$('.tab').forEach(b=>b.onclick=()=>{ $$('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#faq-list').hidden=b.dataset.tab!=='faq';$('#gap-list').hidden=b.dataset.tab!=='gaps'});
async function loadCuration(){try{const [faqs,gaps]=await Promise.all([api('/faqs'),api('/gaps')]);$('#faq-count').textContent=faqs.filter(x=>x.status==='candidate').length;$('#gap-count').textContent=gaps.filter(x=>x.status!=='resolved').length;$('#faq-list').innerHTML=faqs.length?faqs.map(f=>`<article class="curation-item"><div class="curation-top"><div><div class="curation-question">${esc(f.question)}</div><div class="curation-meta">聚合 ${f.count} 次提问 · ${new Date(f.created*1000).toLocaleString()}</div></div><span class="status ${f.status==='published'?'published':''}">${{candidate:'待审核',published:'已发布',rejected:'已驳回'}[f.status]}</span></div><textarea class="curation-answer" data-answer="${f.id}" placeholder="审核并编辑标准答案">${esc(f.answer)}</textarea><div class="curation-actions"><button class="secondary" data-faq-reject="${f.id}">驳回</button><button class="primary" data-faq-publish="${f.id}">保存并发布</button></div></article>`).join(''):'<div class="empty-state">还没有候选 FAQ。相同问题的记录会自动聚合。</div>';$('#gap-list').innerHTML=gaps.length?gaps.map(g=>`<article class="curation-item"><div class="curation-top"><div><div class="curation-question">${esc(g.question)}</div><div class="curation-meta">${esc(g.department||'未知部门')} · ${g.count} 次 · ${new Date(g.created*1000).toLocaleString()}</div></div><select data-gap="${g.id}" class="status-select"><option value="open" ${g.status==='open'?'selected':''}>待处理</option><option value="in_progress" ${g.status==='in_progress'?'selected':''}>处理中</option><option value="resolved" ${g.status==='resolved'?'selected':''}>已解决</option></select></div></article>`).join(''):'<div class="empty-state">暂无知识缺口</div>';$$('[data-faq-publish]').forEach(b=>b.onclick=()=>saveFaq(b.dataset.faqPublish,'published'));$$('[data-faq-reject]').forEach(b=>b.onclick=()=>saveFaq(b.dataset.faqReject,'rejected'));$$('[data-gap]').forEach(s=>s.onchange=async()=>{try{await api(`/gaps/${s.dataset.gap}`,{method:'PUT',body:JSON.stringify({status:s.value})});await loadCuration()}catch(e){toast(e.message)}})}catch(e){toast(e.message)}}
async function saveFaq(id,status){const f=await api('/faqs');const old=f.find(x=>x.id===id);const answer=$(`[data-answer="${CSS.escape(id)}"]`)?.value??old.answer;try{await api(`/faqs/${id}`,{method:'PUT',body:JSON.stringify({question:old.question,answer,status})});await loadCuration();toast(status==='published'?'FAQ 已发布并启用缓存':'FAQ 已驳回')}catch(e){toast(e.message)}}
function departmentOptions(selected='',exclude=''){return '<option value="">无上级部门</option>'+state.departments.filter(d=>d.id!==exclude).map(d=>`<option value="${d.id}" ${selected===d.id?'selected':''}>${esc(d.name)}</option>`).join('')}
function departmentName(id){return state.departments.find(d=>d.id===id)?.name||'未分配'}
async function loadOrganization(){try{[state.departments,state.users,state.roles]=await Promise.all([api('/departments'),api('/users'),api('/roles')]);const byId=new Map(state.departments.map(d=>[d.id,d]));const depth=d=>{let n=0,p=d.parent_id,seen=new Set();while(p&&byId.has(p)&&!seen.has(p)){seen.add(p);n++;p=byId.get(p).parent_id}return n};$('#department-parent').innerHTML=departmentOptions(state.editingDepartment?.parent_id||'',state.editingDepartment?.id||'');$('#new-user-dept').innerHTML='<option value="">无所属部门</option>'+state.departments.map(d=>`<option value="${d.id}">${'　'.repeat(depth(d))}${esc(d.name)}</option>`).join('');$('#new-user-roles').innerHTML=state.roles.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('');$('#departments').innerHTML=state.departments.map(d=>`<div class="department-row"><span>${'　'.repeat(depth(d))}${esc(d.name)} <small>${state.users.filter(u=>u.department_id===d.id).length} 人</small></span><span><button class="row-action" data-dept-edit="${d.id}">编辑</button><button class="row-action danger" data-dept-delete="${d.id}">删除</button></span></div>`).join('');const permissionLabels={'dashboard.view':'运营概览','knowledge.manage':'知识维护','chat.access':'AI 问答','curation.manage':'知识沉淀','organization.manage':'组织与账号'};$('#roles').innerHTML=state.roles.map(r=>`<div class="department-row"><span>${esc(r.name)}${r.built_in?' <small>内置</small>':''}<small class="role-permissions">${r.permissions.map(p=>permissionLabels[p]||p).join('、')||'无功能权限'}</small></span><span><button class="row-action" data-role-edit="${r.id}">编辑</button>${r.built_in?'':'<button class="row-action danger" data-role-delete="'+r.id+'">删除</button>'}</span></div>`).join('');$('#user-rows').innerHTML=state.users.map(u=>`<tr><td><div class="doc-title">${esc(u.display_name)}</div><div class="doc-file">${esc(u.username)}</div></td><td>${esc(departmentName(u.department_id))}</td><td>${u.roles.map(id=>`<span class="tag">${esc(state.roles.find(r=>r.id===id)?.name||id)}</span>`).join(' ')}</td><td><span class="status ${u.active?'published':''}">${u.active?'启用':'停用'}</span></td><td><button class="row-action" data-user-edit="${u.id}">编辑</button><button class="row-action" data-user-status="${u.id}" data-active="${u.active?0:1}">${u.active?'停用':'启用'}</button></td></tr>`).join('');$$('[data-dept-edit]').forEach(b=>b.onclick=()=>editDepartment(b.dataset.deptEdit));$$('[data-dept-delete]').forEach(b=>b.onclick=()=>deleteDepartment(b.dataset.deptDelete));$$('[data-role-edit]').forEach(b=>b.onclick=()=>editRole(b.dataset.roleEdit));$$('[data-role-delete]').forEach(b=>b.onclick=()=>deleteRole(b.dataset.roleDelete));$$('[data-user-edit]').forEach(b=>b.onclick=()=>editUser(b.dataset.userEdit));$$('[data-user-status]').forEach(b=>b.onclick=()=>toggleUserStatus(b.dataset.userStatus,b.dataset.active==='1'))}catch(e){toast(e.message)}}
async function toggleUserStatus(id,active){try{await api(`/users/${id}/status`,{method:'PATCH',body:JSON.stringify({active})});await loadOrganization()}catch(e){toast(e.message)}}
function openUserForm(user=null){state.editingUser=user?.id||null;const form=$('#add-user-form');form.reset();$('#user-form-title').textContent=user?'编辑用户':'创建用户';form.username.disabled=!!user;form.password.hidden=!!user;form.password.required=!user;form.display_name.value=user?.display_name||'';$('#new-user-dept').value=user?.department_id||'';[...$('#new-user-roles').options].forEach(o=>o.selected=user?user.roles.includes(o.value):o.value==='user');$('#add-user-form-wrap').hidden=false}
function editUser(id){openUserForm(state.users.find(u=>u.id===id))}
$('#add-user-toggle').onclick=()=>openUserForm();$('#cancel-user-edit').onclick=()=>{state.editingUser=null;$('#add-user-form-wrap').hidden=true};$('#add-user-form').onsubmit=async e=>{e.preventDefault();const data={display_name:e.currentTarget.display_name.value.trim(),department_id:e.currentTarget.department_id.value||null,roles:[...$('#new-user-roles').selectedOptions].map(o=>o.value)};try{if(state.editingUser)await api(`/users/${state.editingUser}`,{method:'PUT',body:JSON.stringify(data)});else{data.username=e.currentTarget.username.value.trim();data.password=e.currentTarget.password.value;await api('/users',{method:'POST',body:JSON.stringify(data)})}state.editingUser=null;e.currentTarget.reset();e.currentTarget.username.disabled=false;e.currentTarget.password.hidden=false;$('#add-user-form-wrap').hidden=true;await loadOrganization()}catch(err){toast(err.message)}};
$('#department-form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));data.name=data.name.trim();data.parent_id=data.parent_id||null;try{if(state.editingDepartment)await api(`/departments/${state.editingDepartment.id}`,{method:'PUT',body:JSON.stringify(data)});else await api('/departments',{method:'POST',body:JSON.stringify(data)});state.editingDepartment=null;e.currentTarget.reset();$('#department-save').textContent='添加';$('#department-cancel').hidden=true;await loadOrganization()}catch(err){toast(err.message)}};
function editDepartment(id){const d=state.departments.find(x=>x.id===id);state.editingDepartment=d;$('#department-form [name="name"]').value=d.name;$('#department-parent').innerHTML=departmentOptions(d.parent_id,d.id);$('#department-save').textContent='保存';$('#department-cancel').hidden=false}
$('#department-cancel').onclick=()=>{state.editingDepartment=null;$('#department-form').reset();$('#department-parent').innerHTML=departmentOptions();$('#department-save').textContent='添加';$('#department-cancel').hidden=true};
async function deleteDepartment(id){try{await api(`/departments/${id}`,{method:'DELETE'});await loadOrganization()}catch(e){toast(e.message)}}
$('#role-form').onsubmit=async e=>{e.preventDefault();const data={name:e.currentTarget.querySelector('[name="name"]').value.trim(),permissions:[...e.currentTarget.querySelectorAll('[name="permissions"]:checked')].map(x=>x.value)};try{if(state.editingRole)await api(`/roles/${state.editingRole}`,{method:'PUT',body:JSON.stringify(data)});else await api('/roles',{method:'POST',body:JSON.stringify(data)});state.editingRole=null;e.currentTarget.reset();$('#role-save').textContent='添加角色';$('#role-cancel').hidden=true;await loadOrganization()}catch(err){toast(err.message)}};
function editRole(id){const role=state.roles.find(r=>r.id===id);state.editingRole=id;$('#role-form [name="name"]').value=role.name;$$('#role-form [name="permissions"]').forEach(x=>x.checked=role.permissions.includes(x.value));$('#role-save').textContent='保存角色';$('#role-cancel').hidden=false}
$('#role-cancel').onclick=()=>{state.editingRole=null;$('#role-form').reset();$('#role-save').textContent='添加角色';$('#role-cancel').hidden=true};
async function deleteRole(id){try{await api(`/roles/${id}`,{method:'DELETE'});await loadOrganization()}catch(e){toast(e.message)}}
function toast(message){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.style.cssText='position:fixed;right:22px;bottom:22px;background:#26332c;color:white;padding:11px 15px;font-size:12px;z-index:20;max-width:calc(100vw - 44px)';document.body.append(el)}el.textContent=message;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,3200)}
if(state.token)showApp();
